version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    env_file:
      - deploy/db/.env
    volumes:
      - ./deploy/db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - docker.env
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres-data:
